### ISSUE TITLE
Write the original configuration to device, but the devices could not bootup

### ISSUE THREAD

**Issue by yeganlin** [westerndigitalcorporation/ufs-tool#38]
I do a test. 
I first read the configuration descriptor from device and then write the same file to device, as below:
./ufs-utils-debug desc -t 1 -D config-desc.txt -p /dev/ufs-bsg0
./ufs-utils-debug desc -t 1 -w config-desc.txt -p /dev/ufs-bsg0

The device could not bootup. 

The configuration is not changed, and the original configuration is directly written to device, why does it cause the device could not bootup, and what is it related to?

**Comment by arthur-simchaev-sndk** [comment]
Looks like the device removed the data. Check the issue with the device producer.
