### ISSUE TITLE
The device path is hard-coded and is not right for the device(kernel 5.10)

### ISSUE THREAD

**Issue by yeganlin** [westerndigitalcorporation/ufs-tool#39]
In files 'ufs_rpmb.c', the UFS_BSG_PATH is hard-coded as below:
#define UFS_BSG_PATH "/dev/ufs-bsg"
ufs_bsg_fd = open(UFS_BSG_PATH, O_RDWR);

The path UFS_BSG_PATH is hard-coded, but in the latest kernel 5.10, the device path is /dev/ufs-bsg0. It could not work. Therefore, it is best to use the incoming path, rather than hard-coded in the code.

**Comment by arthur-simchaev-sndk** [comment]
Correct.  BTW it can be also /dev/bsg/ufs-bsg0. Therefore in case the platform cannot open the path, the tool will read/write the RPMB with the default block numbers : DEFAULT_RPMB_NUM_BLOCKS 64.  In case you need this change please submit PR

Regards
Arthur
